### PR TITLE
deal with hyphens correctly

### LINKED ISSUE #64: Compatibility regarding hyphens with npm version parsing
Some *weirder* examples which are parsed successfully with npm but not with this library:
```
failed to parse version of cordova, version: 3.0.0-rc1-1
failed to parse version of npm, version: 1.5.0-alpha-0
failed to parse version of karma, version: 0.12.11-beta-3029418
```

### PR DESCRIPTION
**Pull request by steveklabnik**
Fixes #64

### CODE REVIEW

File: src/parser.rs [hunk 1]
```diff
@@ -33,6 +33,8 @@ fn number(i: &[u8]) -> IResult<&[u8], u64> {
 fn ascii_or_hyphen(chr: u8) -> bool {
     // dot
     chr == 46 ||
+    // dot
```
Comment (globin) [inline src/parser.rs]: hyphen?

Comment (steveklabnik) [inline src/parser.rs]: lol sigh :(
